// =====================================
// This file is generated by data model
// =====================================

namespace SimCivil.Concept.ItemModel
{
    public enum MagicElement
    {
        /// <summary>
        /// The N/A - Not an Element
        /// </summary>
        Nae,

        /// <summary>
        /// The Element1
        /// </summary>
        Element1,

        /// <summary>
        /// The Element2
        /// </summary>
        Element2,

        /// <summary>
        /// The Element3
        /// </summary>
        Element3,

    }
}