using System.Collections.Generic;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public enum Compound
    {
        Hydrogen,
        Oxygen,
        Water,
        Wood,
        Iron,
    }

    public static class Compounds
    {
        private struct Property
        {
            public double Density;
            public IReadOnlyDictionary<Element, double> Elements;
        }


        private static IReadOnlyDictionary<Compound, Property> Properties { get; } = new Dictionary<Compound, Property>
        {
            {
                Compound.Hydrogen, new Property()
                {
                    Density = 0.1,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 1 }
                    },
                }
            },
            {
                Compound.Oxygen, new Property()
                {
                    Density = 1.2,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.O, 1 }
                    },
                }
            },
            {
                Compound.Water, new Property()
                {
                    Density = 1000,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 2 },
                        { Element.O, 1 }
                    },
                }
            },
            {
                Compound.Wood, new Property()
                {
                    Density = 500,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 2 },
                        { Element.O, 1 },
                        { Element.C, 3 },
                    },
                }
            },
            {
                Compound.Iron, new Property()
                {
                    Density = 3000,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.Fe, 2 },
                    },
                }
            },
        };

        public static double GetDensity(this Compound com)
        {
            return Properties[com].Density;
        }
        public static IReadOnlyDictionary<Element, double> GetElements(this Compound com)
        {
            return Properties[com].Elements;
        }
    }
}
