using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public enum CompoundType
    {
        None,
        Hydrogen,
        Oxygen,
        Water,
        Wood,
        Iron,
    }

    public struct CompoundProperty
    {
        public double Density;
        public double MeltPoint;
        public double BoilPoint;
        public double FlashPoint;
        public IReadOnlyDictionary<Element, double> Elements;
    }

    public class CompoundData
    {
        public static CompoundData Instance { get; } = new CompoundData();

        private CompoundData() { }

        public IReadOnlyDictionary<CompoundType, CompoundProperty> Properties { get; } = new Dictionary<CompoundType, CompoundProperty>
        {
            {
                CompoundType.Hydrogen, new CompoundProperty()
                {
                    Density = 0.1,
                    MeltPoint = 1,
                    BoilPoint = 2,
                    FlashPoint = 2,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 1 }
                    },
                }
            },
            {
                CompoundType.Oxygen, new CompoundProperty()
                {
                    Density = 1.2,
                    MeltPoint = 10,
                    BoilPoint = 100,
                    FlashPoint = 100,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.O, 1 }
                    },
                }
            },
            {
                CompoundType.Water, new CompoundProperty()
                {
                    Density = 1000,
                    MeltPoint = 273,
                    BoilPoint = 373,
                    FlashPoint = 273,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 2 },
                        { Element.O, 1 }
                    },
                }
            },
            {
                CompoundType.Wood, new CompoundProperty()
                {
                    Density = 500,
                    MeltPoint = 473,
                    BoilPoint = 474,
                    FlashPoint = 273,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.H, 2 },
                        { Element.O, 1 },
                        { Element.C, 3 },
                    },
                }
            },
            {
                CompoundType.Iron, new CompoundProperty()
                {
                    Density = 3000,
                    MeltPoint = 1000,
                    BoilPoint = 2000,
                    FlashPoint = 2000,
                    Elements = new Dictionary<Element, double>()
                    {
                        { Element.Fe, 2 },
                    },
                }
            },
        };

        public double GetProperty(CompoundType compound)
        {
            return Properties[compound].Density;
        }

        public IReadOnlyDictionary<Element, double> GetElements(CompoundType compound)
        {
            return Properties[compound].Elements;
        }
    }
}
