using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public enum CompoundType
    {
        None,
        Hydrogen,
        Oxygen,
        Water,
        Wood,
        Iron,
    }

    public struct CompoundProperty
    {
        public double Density;
        public double MeltPoint;
        public double BoilPoint;
        public double FlashPoint;
        public IReadOnlyDictionary<Element, double> Elements;
    }

    public class JsonCompoundRepository : ICompoundRepository, IDataLoader
    {
        public static JsonCompoundRepository Instance { get; } = new JsonCompoundRepository();

        private JsonCompoundRepository() { }

        public IReadOnlyDictionary<CompoundType, CompoundProperty> Properties { get; }

        public void LoadData()
        {
            throw new NotImplementedException("Load data into properties.");
        }

        public double GetProperty(CompoundType compound)
        {
            return Properties[compound].Density;
        }

        public IReadOnlyDictionary<Element, double> GetElements(CompoundType compound)
        {
            return Properties[compound].Elements;
        }
    }
}
