using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public enum Element
    {
        H,
        O,
        C,
        Fe,
    }

    public struct ElementProperty
    {
        public string FullName;
    }

    public class ElementData
    {
        public IReadOnlyDictionary<Element, ElementProperty> Properties { get; } = new Dictionary<Element, ElementProperty>
        {
            {
                Element.H,
                new ElementProperty()
                {
                    FullName = "Hydrogen",
                }
            },
            {
                Element.O,
                new ElementProperty()
                {
                    FullName = "Oxygen",
                }
            },
            {
                Element.C,
                new ElementProperty()
                {
                    FullName = "Carbon",
                }
            },
            {
                Element.Fe,
                new ElementProperty()
                {
                    FullName = "Iron",
                }
            },
        };

        public string GetFullName(Element element)
        {
            return Properties[element].FullName;
        }
    }
}
