using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public struct ElementProperty
    {
        public string FullName;
    }

    public class JsonElementRepository : IElementRepository, IDataLoader
    {
        public static JsonElementRepository Instance { get; } = new JsonElementRepository();

        private JsonElementRepository() { }

        public IReadOnlyDictionary<Element, ElementProperty> Properties { get; }

        public void LoadData() {
            throw new NotImplementedException("Load data into properties.");
        }

        public string GetFullName(Element element)
        {
            return Properties[element].FullName;
        }
    }
}
