// =====================================
// This file is generated by data model
// =====================================
using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    public enum Element
    {
		// N/A - Not an Element
        Nae,

		// Hydrogen
        H,

		// Oxygen
        O,

		// Carbon
        C,

		// Iron
        Fe,

    }
}