// =====================================
// This file is generated by data model
// =====================================
using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    public enum Element
    {
        /// <summary>
        /// The N/A - Not an Element
        /// </summary>
        Nae,

        /// <summary>
        /// The Hydrogen
        /// </summary>
        H,

        /// <summary>
        /// The Oxygen
        /// </summary>
        O,

        /// <summary>
        /// The Carbon
        /// </summary>
        C,

        /// <summary>
        /// The Iron
        /// </summary>
        Fe,

    }
}