using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public struct ElementProperty
    {
        public string FullName;
    }

    public class ElementData
    {
        public static ElementData Instance { get; } = new ElementData();

        private ElementData() { }

        public IReadOnlyDictionary<Element, ElementProperty> Properties { get; }

        public void Load() {
            throw new NotImplementedException("Load data into properties.");
        }

        public string GetFullName(Element element)
        {
            return Properties[element].FullName;
        }
    }
}
