// =====================================
// This file is generated by data model
// =====================================
using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    public enum Element
    {
		// N/A
        Nan,

		// Hydrogen
        H,

		// Oxygen
        O,

		// Carbon
        C,

		// Iron
        Fe,

    }
}