using System;
using System.Collections.Generic;
using System.Text;

namespace SimCivil.Concept.ItemModel
{
    /// <summary>
    /// This file will be generated by data model
    /// </summary>
    public enum Element
    {
        H,
        O,
        C,
        Fe,
    }

    public static class Elements
    {
        public static IReadOnlyDictionary<Element, string> FullNames { get; } = new Dictionary<Element, string>
        {
            { Element.H, "Hydrogen"},
            { Element.O, "Oxygen"},
            { Element.C, "Carbon"},
            { Element.Fe, "Iron"},
        };
    }
}
